# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compra',
            new_name='Venda',
        ),
    ]
